[tool.poetry]
name = "ssvc"
version = "1.0.2"
description = "A Python implementation of the Stakeholder-Specific Vulnerability Categorization framework."
authors = ["Christopher Langton <chris@langton.cloud>"]
readme = "PYPI.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]
uv = "^0.1.29"
isort = "^5.13.2"
pytest = "^8.1.1"
pytest-cov = "^5.0.0"
coverage-badge = "^1.1.0"
ruff = "^0.3.5"
poetry = "^1.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Repository" = "https://github.com/chrisdlangton/py-cisa-ssvc.git"
